# Generated by Django 4.2.1 on 2023-11-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
                ("nota_primeiro_semestre", models.CharField(max_length=5)),
                ("nota_segundo_semestre", models.CharField(max_length=5)),
                ("nome_professor", models.CharField(max_length=50)),
                ("numero_sala", models.CharField(max_length=4)),
            ],
        ),
    ]
